#######################################Building the Final Edu Index###############################
#Load Libraries
library(tidyverse)

#Import expectedu and meanindex dataframes generated by previous  scripts 

#Select relevant columns from expectedu and meanedu dataframes

expectedu <-expect_edu_index %>%
  select("GEOID", "expect_edu_index")


meanindex <- mean_edu_index %>% 
  select('GEOID', "NAME",'mean_edu_index' )


#Join 2 dataframes and calculate final edu index

final_edu_index <- left_join(meanindex, expectedu, by = 'GEOID')

final_edu_index<- final_edu_index  %>%
  mutate('final_edu_index' = case_when( is.na(expect_edu_index)  | expect_edu_index == "NaN" ~ mean_edu_index,
                                        TRUE ~ ((mean_edu_index)+(expect_edu_index))/2
    
  ))

#Save Data

write.csv(final_edu_index, 'final_edu_index.csv')
