#######################################Building the Final Edu Index###############################

#Import expectedu and meanindex dataframes generated by previous  scripts 

#Select relevant columns from expectedu dataframe

expectedu <-expectedu[c('GEOID', 'expecteduindex')]

expectedu <- rename(expectedu, "FIPS"="GEOID")

#Make seperate column of FIPS codes for meanindex dataframe for 
#easy joining with expectedu dataframe (since expectedu is at county level 
# and meanindex is at census tract level)

meanindex <- meanindex[c('GEOID', "NAME",'meanyearsofschoolindex' )]

meanindex$FIPS <- substr(meanindex$GEOID, 1,5)

#Join 2 dataframes and calculate final edu index

final_edu_index <- left_join(meanindex, expectedu, by = 'FIPS')

final_edu_index$finaleduindex <- ((final_edu_index$meanyearsofschoolindex)
                                  +(final_edu_index$expecteduindex))/2
